spring:
  profiles:
    active: dev
  application:
    name: springboot-demo

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    com.example.demo: INFO
    org.springframework.security: DEBUG
